"use client";

import { FormEvent, useEffect, useState } from "react";

const whatsApp = "https://wa.me/905338877740";
type Kind = "home" | "catalog" | "manufacturers" | "contact";
const nav = [["Home", "/index.html", "home"], ["Catalog", "/catalog.html", "catalog"], ["Manufacturers", "/verified-manufacturers.html", "manufacturers"], ["Contact", "/contact.html", "contact"]] as const;
const products = [
  ["Surgical instruments", "Precision instruments", "Hand-finished essentials for oral surgery, periodontics and restorative care.", "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1100&q=85", "ASA Dental Italian Surgical Instruments"],
  ["Rotary & restorative", "Everyday clinical performance", "Reliable handpieces, burs and restorative accessories for busy practices.", "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1100&q=85", "Dental handpiece and restorative supplies for clinics"],
  ["Practice essentials", "Stock with confidence", "Curated consumables and clinical basics selected for consistent supply planning.", "https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1100&q=85", "Premium dental practice consumables and clinical essentials"],
] as const;

/** Shared page composition. All editable content and reusable site sections live here. */
export function SitePage({ page = "home" }: { page?: Kind }) {
  const [lang, setLang] = useState("EN"); const [country, setCountry] = useState("Turkey"); const [open, setOpen] = useState(false);
  useEffect(() => { document.documentElement.lang = lang === "TR" ? "tr" : lang === "AR" ? "ar" : "en"; document.documentElement.dir = lang === "AR" ? "rtl" : "ltr"; }, [lang]);
  return <><div className="announcement">Delivering verified dental supply solutions across Turkey &amp; Iraq</div><header className="site-header"><a className="brand" href="/index.html"><i>T</i><span>TAMMUZ <em>MEDICAL</em></span></a><button className="menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>Menu</button><nav className={open ? "nav open" : "nav"}>{nav.map(([label, href, key]) => <a key={href} className={key === page ? "active" : ""} href={href}>{label}</a>)}</nav><div className="tools"><select value={country} aria-label="Country" onChange={e => setCountry(e.target.value)}><option>Turkey</option><option>Iraq</option><option>Other</option></select><span>{["EN", "TR", "AR"].map(x => <button className={x === lang ? "selected" : ""} onClick={() => setLang(x)} key={x}>{x}</button>)}</span></div></header><main>{page === "home" ? <Home country={country} /> : page === "catalog" ? <Catalog /> : page === "manufacturers" ? <Manufacturers /> : <Contact />}</main><Footer /><a className="wa" href={whatsApp} target="_blank" rel="noreferrer" aria-label="Chat with Tammuz Medical on WhatsApp">WA <span>WhatsApp</span></a></>;
}

function Home({ country }: { country: string }) { return <><section className="hero"><div className="hero-copy"><Eyebrow>Italian dental expertise, locally supplied</Eyebrow><h1>Premium Dental Supplies for Turkish Clinics &amp; Distributors</h1><p className="lede">A trusted B2B partner for clinics, distributors and procurement teams across {country}. Source quality-led ASA Dental products with a clear, responsive supply process.</p><div className="buttons"><a className="button primary" href={whatsApp} target="_blank" rel="noreferrer">Chat on WhatsApp ↗</a><a className="button" href="/catalog.html">View Full Catalog ↓</a></div><div className="stats"><b>20+<small>Years of sourcing experience</small></b><b>2<small>Regional operating markets</small></b><b>1:1<small>Dedicated account support</small></b></div></div><div className="hero-art" role="img" aria-label="Premium Italian dental instruments arranged for clinical supply procurement"><div className="art-card"><span>VERIFIED SUPPLY</span><div className="instrument a"/><div className="instrument b"/><div className="instrument c"/><p>Better instruments.<br/><em>Better outcomes.</em></p></div><small>● Turkey · Iraq</small></div></section><Trust /><section className="section"><Heading eyebrow="Selected for clinical confidence" title="Featured dental categories" link="Explore all products"/><Products /></section><section className="story"><div className="italy" role="img" aria-label="Italian dental manufacturing story"><b>MADE IN<br/>ITALY</b><span>✦</span></div><div className="story-copy"><Eyebrow>Our manufacturing partner</Eyebrow><h2>Italian craft, built for everyday clinical precision.</h2><p>ASA Dental combines technical expertise and Italian manufacturing tradition to create instruments that feel balanced in the hand and perform reliably in practice.</p><p>We bring its professional portfolio closer to buyers in Turkey and Iraq—with product guidance that makes confident selection straightforward.</p><a className="text-link" href="/verified-manufacturers.html">Meet ASA Dental →</a></div></section><section className="section sourcing"><div><Eyebrow>The Tammuz approach</Eyebrow><h2>Supply should be the easy part of your day.</h2><p>From first product list to final inspection, we make a detailed sourcing process clear, considered and accountable.</p></div><div className="processes">{[["01","Specify","Tell us what your practice, distributor network or tender requires."],["02","Source","We match verified products, quantities and documentation."],["03","Inspect","Every order is checked before dispatch."],["04","Deliver","Regional logistics and responsive support keep supply moving."]].map(x => <article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><Quote /></>; }
function Trust() { return <section className="trust"><h3>Built on verifiable standards</h3><div><p><b>ISO</b>ISO 13485<br/>Certified</p><p><b>CE</b>CE Mark<br/>Compliant</p><p><b>ASA</b>ASA Dental<br/>Partner</p><p><b>✓</b>Pre-Shipment<br/>Inspection</p></div></section>; }
function Products() { return <div className="products">{products.map(([category,title,text,image,alt]) => <article key={title}><img src={image} alt={alt}/><div><small>{category}</small><h3>{title}</h3><p>{text}</p><a href="/catalog.html">Explore →</a></div></article>)}</div>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span/> {children}</p>; }
function Heading({ eyebrow,title,link }: { eyebrow:string;title:string;link:string }) { return <div className="heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div><a className="text-link" href="/catalog.html">{link} →</a></div>; }
function Quote() { const [sent,setSent] = useState(false); function submit(e:FormEvent){e.preventDefault();setSent(true)} return <section id="quote" className="quote"><div><Eyebrow>Start a conversation</Eyebrow><h2>Let&apos;s build your next supply order.</h2><p>Send a brief or product list and our team will respond with availability, documentation and next steps.</p><a href="tel:+905338877740">+90 533 887 77 40</a><a href={whatsApp} target="_blank" rel="noreferrer">WhatsApp quick-chat ↗</a></div><form onSubmit={submit}><div className="form-row"><label>Full name<input required placeholder="Your name"/></label><label>Company<input required placeholder="Company / clinic"/></label></div><div className="form-row"><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Country<select><option>Turkey</option><option>Iraq</option><option>Other</option></select></label></div><label>What are you looking for?<textarea required rows={4} placeholder="Products, quantities, or an outline of your requirement"/></label><button className="button primary">Request a quote →</button>{sent && <p className="success">Thank you—your request has been received. We&apos;ll be in touch shortly.</p>}</form></section>; }
function PageHero({ eyebrow,title,text }: { eyebrow:string;title:string;text:string }) { return <section className="page-hero"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{text}</p></section>; }
function Catalog() { return <><PageHero eyebrow="Browse the portfolio" title="A considered catalog for modern dental practices." text="Explore product families selected for clinical performance, dependable availability and documentation-ready procurement."/><section className="section"><div className="filters"><b>All categories</b><span>Instruments</span><span>Restorative</span><span>Endodontics</span><span>Implantology</span><span>Consumables</span></div><Products /><div className="note"><p>Need a specific ASA Dental reference?</p><a className="button primary" href="#quote">Request a product list →</a></div></section><Quote/></>; }
function Manufacturers() { return <><PageHero eyebrow="Verified manufacturing" title="Manufacturing partnerships you can stand behind." text="We select suppliers with the technical discipline, quality systems and service orientation our market expects."/><section className="section manufacturer"><div className="asa">ASA<span>DENTAL</span><small>ITALY</small></div><div><Eyebrow>Featured partner</Eyebrow><h2>ASA Dental</h2><p className="large">Italian manufacturer of professional dental instruments and solutions, established on a tradition of precision and practical innovation.</p><div className="details"><p><b>Origin</b>Italy</p><p><b>Focus</b>Dental instruments &amp; equipment</p><p><b>Assurance</b>ISO 13485 / CE compliance</p></div></div></section><section className="section values"><div><Eyebrow>Our sourcing promise</Eyebrow><h2>Every partnership is checked against the same standard.</h2></div><div><p><b>01</b>Product quality that holds up in daily clinical use.</p><p><b>02</b>Clear technical information and supporting documentation.</p><p><b>03</b>Reliable supply relationships—not transactional listings.</p></div></section><Quote/></>; }
function Contact() { return <><PageHero eyebrow="Contact Tammuz Medical" title="A direct route to the right supply solution." text="Whether you need product guidance, distributor pricing or a formal quote, our team is ready to help."/><section className="contact"><div><Eyebrow>Get in touch</Eyebrow><h2>Talk to our sourcing team.</h2><a href="tel:+905338877740">+90 533 887 77 40</a><a href={whatsApp} target="_blank" rel="noreferrer">WhatsApp quick-chat ↗</a><p>Serving clinics, distributors and procurement teams in Turkey and Iraq.</p><div className="coverage"><b>Turkey</b><b>Iraq</b><small>Regional supply coverage</small></div></div><Quote/></section></>; }
function Footer() { return <footer><div className="footer-top"><div><a className="brand" href="/index.html"><i>T</i><span>TAMMUZ <em>MEDICAL</em></span></a><p>Premium dental and medical supply solutions for Turkey and Iraq.</p></div><div className="footer-nav"><div><b>Explore</b>{nav.map(([l,h])=><a key={h} href={h}>{l}</a>)}</div><div><b>Contact</b><a href="tel:+905338877740">+90 533 887 77 40</a><a href={whatsApp}>WhatsApp</a><a href="mailto:info@tammuzmedical.com">info@tammuzmedical.com</a></div></div></div><div className="legal"><p>© {new Date().getFullYear()} Tammuz Medical. All rights reserved.</p><p>Demozi Kozmetik ve Makina Dış Ticaret Ltd. Şti. (Turkey)<br/>Mega Standard General Trading LLC (Iraq)</p></div></footer>; }
